/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF, Center, Bounds } from '@react-three/drei'
import LayerStack from './LayerStack'

export default function Bunny() {
  const { nodes } = useGLTF('/bunny.glb') as any
  return (
    <Bounds fit>
      <Center>
        <mesh matrixAutoUpdate geometry={nodes.Object_2.geometry} rotation-y={Math.PI / 2} scale={30}>
          <LayerStack />
        </mesh>
      </Center>
    </Bounds>
  )
}

useGLTF.preload('/bunny.glb')
