/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF, Center } from '@react-three/drei'
import LayerStack from './LayerStack'

export default function Duck() {
  const { nodes, materials } = useGLTF('/duck.glb') as any
  return (
    <Center>
      <mesh
        matrixAutoUpdate
        geometry={nodes.defaultMaterial.geometry} //
        rotation-x={-Math.PI / 2}
        scale={0.01}
      >
        <LayerStack />
      </mesh>
    </Center>
  )
}

useGLTF.preload('/duck.glb')
