/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useState } from 'react'
import { useGLTF, TransformControls, OrbitControls, useTexture } from '@react-three/drei'
import { LaminaDebugger } from 'lamina/debug'
import * as LAYERS from 'lamina'
import { button, useControls } from 'leva'
import { MathUtils } from 'three'

export default function Monkey() {
  const { nodes } = useGLTF('/monkey.glb') as any
  const orbitControls = React.useRef<any>(null!)
  const transformControls = React.useRef<any>(null!)

  React.useEffect(() => {
    if (transformControls.current) {
      const { current: controls } = transformControls
      const callback = (event: any) => (orbitControls.current.enabled = !event.value)
      controls.addEventListener('dragging-changed', callback)
      return () => controls.removeEventListener('dragging-changed', callback)
    }
  })

  const [layers, setLayers] = useState<any[]>([])
  const InitialMaterial = LAYERS.useLamina('/initialMaterial.json')

  useControls('Layers', {
    Type: {
      options: [
        'Abstract', //
        'Color',
        'Depth',
        'Displace',
        'Fresnel',
        'Gradient',
        'Matcap',
        'Noise',
        'Texture',
      ],
      value: 'Color',
    },
    Add: button((get) => {
      const k = get('Layers.Type')
      // @ts-ignore
      const Component = LAYERS[k]
      setLayers((s) => [...s, Component])
    }),
  })

  const tex = useTexture('/UV.jpg')
  return (
    <>
      <TransformControls ref={transformControls}>
        <group scale={0.1} rotation={[0, -Math.PI / 2, Math.PI / 4]}>
          <mesh matrixAutoUpdate geometry={nodes.Suzanne.geometry} rotation-y={Math.PI / 2} scale={30}>
            <LaminaDebugger>
              {/* <InitialMaterial>
                {layers.map((Layer, i) => (
                  <Layer key={`layer-${i}`} />
                ))}
              </InitialMaterial> */}
              <LAYERS.LayerMaterial>
                <LAYERS.Texture map={tex} />
                {layers.map((Layer, i) => (
                  <Layer key={`layer-${i}`} />
                ))}
              </LAYERS.LayerMaterial>
            </LaminaDebugger>
          </mesh>
        </group>
      </TransformControls>
      <OrbitControls ref={orbitControls} />
    </>
  )
}

useGLTF.preload('/monkey.glb')
